const nganHangDe = {
  "thongTin": {
    "mon": "Ngữ văn",
    "khoi": "8",
    "ten": "Ngân hàng câu hỏi Ngữ văn 8",
    "phienBan": "2.0",
    "phamVi": "Toàn bộ kiến thức lớp 6 + toàn bộ kiến thức lớp 7 + Bài 1, Bài 2 lớp 8"
  },
  "cauHoi": [
    {
      "maCau": "VAN8-0001",
      "loai": "MCQ",
      "cauHoi": "Nhân vật trong truyện thường được khắc họa qua những phương diện nào?",
      "A": "ngoại hình, hành động, lời nói, suy nghĩ",
      "B": "chỉ tên",
      "C": "chỉ tuổi",
      "D": "chỉ quê quán",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tôi và các bạn",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0002",
      "loai": "MCQ",
      "cauHoi": "Cốt truyện là gì?",
      "A": "chuỗi sự việc được tổ chức thành câu chuyện",
      "B": "danh sách nhân vật",
      "C": "tiểu sử tác giả",
      "D": "tên tác phẩm",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tôi và các bạn",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0003",
      "loai": "MCQ",
      "cauHoi": "Ngôi kể thứ nhất thường dùng đại từ nào?",
      "A": "tôi",
      "B": "hắn",
      "C": "nó",
      "D": "họ",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tôi và các bạn",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0004",
      "loai": "TRUEFALSE",
      "cauHoi": "Người kể chuyện luôn chính là tác giả ngoài đời.",
      "dapAn": "Sai",
      "diem": 1,
      "chuDe": "Tôi và các bạn",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0005",
      "loai": "MCQ",
      "cauHoi": "Văn bản về gia đình thường làm nổi bật giá trị nào?",
      "A": "tình yêu thương và gắn bó",
      "B": "cạnh tranh",
      "C": "vật chất",
      "D": "danh vọng",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Gõ cửa trái tim",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0006",
      "loai": "MULTI",
      "cauHoi": "Một bài nói về vấn đề gia đình nên có những gì?",
      "A": "quan điểm rõ",
      "B": "lí lẽ phù hợp",
      "C": "ví dụ cụ thể",
      "D": "nói thật nhanh",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Gõ cửa trái tim",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0007",
      "loai": "MCQ",
      "cauHoi": "Khi trình bày ý kiến, cần làm gì trước?",
      "A": "xác định rõ vấn đề",
      "B": "đọc thuộc mọi thứ",
      "C": "không cần chuẩn bị",
      "D": "chỉ chọn hình ảnh",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Gõ cửa trái tim",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0008",
      "loai": "MCQ",
      "cauHoi": "Khi phân tích nhân vật, bằng chứng nên lấy từ đâu?",
      "A": "chi tiết trong văn bản",
      "B": "tin đồn",
      "C": "quảng cáo",
      "D": "ý kiến không căn cứ",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Yêu thương và chia sẻ",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0009",
      "loai": "TRUEFALSE",
      "cauHoi": "Phân tích nhân vật chỉ cần kể lại cốt truyện.",
      "dapAn": "Sai",
      "diem": 1,
      "chuDe": "Yêu thương và chia sẻ",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0010",
      "loai": "MCQ",
      "cauHoi": "Thơ lục bát gồm cặp câu cơ bản như thế nào?",
      "A": "6 tiếng và 8 tiếng",
      "B": "4 tiếng và 5 tiếng",
      "C": "5 tiếng và 7 tiếng",
      "D": "7 tiếng và 7 tiếng",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Quê hương yêu dấu",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0011",
      "loai": "MCQ",
      "cauHoi": "Ca dao gắn với điều gì?",
      "A": "đời sống và tình cảm nhân dân",
      "B": "khoa học",
      "C": "luật pháp",
      "D": "tin tức",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Quê hương yêu dấu",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0012",
      "loai": "FILL",
      "cauHoi": "Thể thơ gồm câu sáu tiếng và câu tám tiếng gọi là ________.",
      "dapAn": "lục bát",
      "diem": 1,
      "chuDe": "Quê hương yêu dấu",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0013",
      "loai": "MCQ",
      "cauHoi": "Du kí thường ghi lại điều gì?",
      "A": "trải nghiệm, quan sát và cảm nhận",
      "B": "công thức",
      "C": "luật chơi",
      "D": "bảng số liệu",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Những nẻo đường xứ sở",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0014",
      "loai": "TRUEFALSE",
      "cauHoi": "Du kí có thể kết hợp kể, tả và biểu cảm.",
      "dapAn": "Đúng",
      "diem": 1,
      "chuDe": "Những nẻo đường xứ sở",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0015",
      "loai": "MCQ",
      "cauHoi": "Khi kể về chuyến đi, nên kết hợp sự việc với gì?",
      "A": "quan sát và cảm xúc",
      "B": "chỉ số liệu",
      "C": "chỉ lời thoại",
      "D": "chỉ nhận xét",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Những nẻo đường xứ sở",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0016",
      "loai": "MCQ",
      "cauHoi": "“Thánh Gióng” thuộc thể loại nào?",
      "A": "truyền thuyết",
      "B": "truyện cười",
      "C": "tản văn",
      "D": "kí",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Chuyện kể về những người anh hùng",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0017",
      "loai": "MCQ",
      "cauHoi": "“Sơn Tinh, Thủy Tinh” gắn với hiện tượng nào?",
      "A": "lũ lụt",
      "B": "động đất",
      "C": "sương mù",
      "D": "hạn hán",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Chuyện kể về những người anh hùng",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0018",
      "loai": "MULTI",
      "cauHoi": "Truyền thuyết thường có những yếu tố nào?",
      "A": "nhân vật/sự kiện gắn lịch sử",
      "B": "yếu tố kì ảo",
      "C": "cách đánh giá của nhân dân",
      "D": "số liệu khoa học bắt buộc",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Chuyện kể về những người anh hùng",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0019",
      "loai": "MCQ",
      "cauHoi": "Đặc điểm thường gặp của truyện cổ tích là gì?",
      "A": "yếu tố kì ảo và ước mơ công bằng",
      "B": "ghi chép lịch sử",
      "C": "số liệu khoa học",
      "D": "không có nhân vật",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Thế giới cổ tích",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0020",
      "loai": "TRUEFALSE",
      "cauHoi": "Cổ tích hoàn toàn không có yếu tố tưởng tượng.",
      "dapAn": "Sai",
      "diem": 1,
      "chuDe": "Thế giới cổ tích",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0021",
      "loai": "MCQ",
      "cauHoi": "Tôn trọng sự khác biệt giúp con người như thế nào?",
      "A": "hiểu và ứng xử văn minh hơn",
      "B": "xa cách hơn",
      "C": "không đối thoại",
      "D": "đánh giá vội vàng",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Khác biệt và gần gũi",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0022",
      "loai": "MCQ",
      "cauHoi": "Khi kể lại một sự việc, yếu tố nào giúp bài viết rõ ràng?",
      "A": "trình tự hợp lí",
      "B": "chỉ tính từ",
      "C": "chỉ đối thoại",
      "D": "không có thời gian",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Khác biệt và gần gũi",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0023",
      "loai": "MCQ",
      "cauHoi": "Mục đích chính của văn bản thông tin là gì?",
      "A": "cung cấp và tổ chức thông tin",
      "B": "chỉ kể chuyện",
      "C": "chỉ biểu cảm",
      "D": "chỉ gây cười",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Trái Đất – ngôi nhà chung",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0024",
      "loai": "MULTI",
      "cauHoi": "Văn bản thông tin có thể sử dụng những yếu tố nào?",
      "A": "tiêu đề",
      "B": "đề mục",
      "C": "số liệu/hình ảnh",
      "D": "nhân vật hư cấu bắt buộc",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Trái Đất – ngôi nhà chung",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0025",
      "loai": "MCQ",
      "cauHoi": "Khi giới thiệu sách nên nêu gì?",
      "A": "tên, tác giả, nội dung và giá trị",
      "B": "chỉ giá tiền",
      "C": "chỉ màu bìa",
      "D": "chỉ số trang",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Cuốn sách tôi yêu",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0026",
      "loai": "TRUEFALSE",
      "cauHoi": "Giới thiệu sách nên nêu lí do vì sao cuốn sách đáng đọc.",
      "dapAn": "Đúng",
      "diem": 1,
      "chuDe": "Cuốn sách tôi yêu",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0027",
      "loai": "MCQ",
      "cauHoi": "Trạng ngữ thường bổ sung thông tin về gì?",
      "A": "thời gian, nơi chốn, nguyên nhân, mục đích...",
      "B": "chỉ chủ ngữ",
      "C": "chỉ số lượng",
      "D": "chỉ tên người",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tiếng Việt 6",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0028",
      "loai": "MCQ",
      "cauHoi": "Thành phần trung tâm của cụm danh từ là gì?",
      "A": "danh từ",
      "B": "động từ",
      "C": "tính từ",
      "D": "phó từ",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tiếng Việt 6",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0029",
      "loai": "MCQ",
      "cauHoi": "Thành phần trung tâm của cụm động từ là gì?",
      "A": "động từ",
      "B": "danh từ",
      "C": "tính từ",
      "D": "quan hệ từ",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tiếng Việt 6",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0030",
      "loai": "MCQ",
      "cauHoi": "Nhân hóa là gì?",
      "A": "gán đặc điểm của con người cho sự vật",
      "B": "đối chiếu",
      "C": "lặp từ",
      "D": "nói giảm",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tiếng Việt 6",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0031",
      "loai": "MCQ",
      "cauHoi": "So sánh giúp cách diễn đạt như thế nào?",
      "A": "cụ thể, sinh động",
      "B": "khó hiểu hơn",
      "C": "không có hình ảnh",
      "D": "chỉ có số liệu",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tiếng Việt 6",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0032",
      "loai": "MCQ",
      "cauHoi": "Điệp ngữ là gì?",
      "A": "lặp lại từ ngữ có chủ ý",
      "B": "dùng từ địa phương",
      "C": "đảo câu",
      "D": "dùng số liệu",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tiếng Việt 6",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0033",
      "loai": "FILL",
      "cauHoi": "Lặp lại từ ngữ có chủ ý để nhấn mạnh gọi là ________.",
      "dapAn": "điệp ngữ",
      "diem": 1,
      "chuDe": "Tiếng Việt 6",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0034",
      "loai": "MCQ",
      "cauHoi": "Dấu ngoặc kép có thể dùng để đánh dấu gì?",
      "A": "lời dẫn trực tiếp hoặc từ ngữ đặc biệt",
      "B": "câu hỏi",
      "C": "chủ ngữ",
      "D": "dấu chấm",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tiếng Việt 6",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0035",
      "loai": "MCQ",
      "cauHoi": "Ẩn dụ là biện pháp gọi tên sự vật dựa trên quan hệ nào?",
      "A": "tương đồng",
      "B": "thời gian",
      "C": "địa điểm",
      "D": "số lượng",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tiếng Việt 6",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0036",
      "loai": "MCQ",
      "cauHoi": "“Bầy chim chìa vôi” tập trung thể hiện thế giới nào?",
      "A": "tuổi thơ và tình cảm trong trẻo",
      "B": "đời sống cung đình",
      "C": "chiến tranh hiện đại",
      "D": "thương mại",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1: Bầu trời tuổi thơ",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0037",
      "loai": "MCQ",
      "cauHoi": "Tóm tắt văn bản cần ưu tiên điều gì?",
      "A": "sự việc chính và trình tự hợp lí",
      "B": "mọi chi tiết",
      "C": "mọi lời thoại",
      "D": "mọi câu văn",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1: Bầu trời tuổi thơ",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0038",
      "loai": "MCQ",
      "cauHoi": "Mở rộng trạng ngữ bằng cụm từ có tác dụng gì?",
      "A": "cung cấp thông tin cụ thể hơn",
      "B": "làm câu sai",
      "C": "xóa trạng ngữ",
      "D": "chỉ đổi dấu câu",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1: Bầu trời tuổi thơ",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0039",
      "loai": "FILL",
      "cauHoi": "Trạng ngữ có thể được mở rộng bằng một ________ để thông tin cụ thể hơn.",
      "dapAn": "cụm từ",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1: Bầu trời tuổi thơ",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0040",
      "loai": "TRUEFALSE",
      "cauHoi": "Tóm tắt là chép lại nguyên văn toàn bộ văn bản.",
      "dapAn": "Sai",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1: Bầu trời tuổi thơ",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0041",
      "loai": "MULTI",
      "cauHoi": "Khi tóm tắt truyện nên giữ gì?",
      "A": "nhân vật chính",
      "B": "sự việc chính",
      "C": "trình tự quan trọng",
      "D": "mọi chi tiết phụ",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1: Bầu trời tuổi thơ",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0042",
      "loai": "MCQ",
      "cauHoi": "Một bản tóm tắt tốt cần như thế nào?",
      "A": "ngắn gọn nhưng đúng nội dung",
      "B": "dài hơn bản gốc",
      "C": "thêm tình tiết",
      "D": "đổi kết thúc",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1: Bầu trời tuổi thơ",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0043",
      "loai": "MCQ",
      "cauHoi": "Khi kể lại một trải nghiệm, chi tiết tiêu biểu giúp gì?",
      "A": "làm câu chuyện tập trung",
      "B": "làm mất mạch",
      "C": "kéo dài vô ích",
      "D": "xóa cảm xúc",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1: Bầu trời tuổi thơ",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0044",
      "loai": "MCQ",
      "cauHoi": "Bài nói về trải nghiệm cần chú ý gì?",
      "A": "trình tự, nội dung và cảm xúc",
      "B": "chỉ tốc độ",
      "C": "chỉ hình ảnh",
      "D": "chỉ số slide",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1: Bầu trời tuổi thơ",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0045",
      "loai": "MCQ",
      "cauHoi": "“Đồng dao mùa xuân” thuộc thể loại nào?",
      "A": "thơ",
      "B": "truyện",
      "C": "kịch",
      "D": "nghị luận",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 2: Khúc nhạc tâm hồn",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0046",
      "loai": "MCQ",
      "cauHoi": "“Gặp lá cơm nếp” gợi nổi bật tình cảm nào?",
      "A": "tình yêu mẹ và quê hương",
      "B": "sự ganh đua",
      "C": "tình yêu vật chất",
      "D": "nỗi sợ",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 2: Khúc nhạc tâm hồn",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0047",
      "loai": "MCQ",
      "cauHoi": "Thơ bốn chữ được nhận biết chủ yếu dựa vào đâu?",
      "A": "số tiếng trong mỗi dòng",
      "B": "số khổ",
      "C": "tên tác giả",
      "D": "số nhân vật",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 2: Khúc nhạc tâm hồn",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0048",
      "loai": "MCQ",
      "cauHoi": "Đoạn văn ghi lại cảm xúc về thơ cần dựa vào gì?",
      "A": "hình ảnh, từ ngữ, nhịp điệu và nội dung",
      "B": "chỉ tiểu sử",
      "C": "chỉ nhan đề",
      "D": "chỉ năm sáng tác",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 2: Khúc nhạc tâm hồn",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0049",
      "loai": "FILL",
      "cauHoi": "Thơ bốn chữ là thể thơ mỗi dòng thường có ________ tiếng.",
      "dapAn": "bốn",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 2: Khúc nhạc tâm hồn",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0050",
      "loai": "TRUEFALSE",
      "cauHoi": "Cảm xúc về bài thơ cần có căn cứ từ văn bản.",
      "dapAn": "Đúng",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 2: Khúc nhạc tâm hồn",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0051",
      "loai": "MULTI",
      "cauHoi": "Khi phân tích thơ có thể chú ý những gì?",
      "A": "hình ảnh",
      "B": "từ ngữ",
      "C": "nhịp điệu",
      "D": "màu giấy",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 2: Khúc nhạc tâm hồn",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0052",
      "loai": "MCQ",
      "cauHoi": "Một đoạn văn cảm xúc tốt cần tránh điều gì?",
      "A": "nhận xét chung chung không có căn cứ",
      "B": "nêu cảm xúc",
      "C": "dẫn hình ảnh",
      "D": "liên hệ",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 2: Khúc nhạc tâm hồn",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0053",
      "loai": "MCQ",
      "cauHoi": "Mạch cảm xúc giúp người đọc hiểu điều gì?",
      "A": "sự vận động của tình cảm và suy nghĩ",
      "B": "số trang",
      "C": "giá sách",
      "D": "nhà in",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 2: Khúc nhạc tâm hồn",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0054",
      "loai": "MATCH",
      "cauHoi": "Nối nội dung với kĩ năng.",
      "pairs": [
        {
          "left": "A. Tóm tắt",
          "right": "1. Giữ sự việc chính"
        },
        {
          "left": "B. Cảm nhận thơ",
          "right": "2. Dựa vào hình ảnh, từ ngữ"
        },
        {
          "left": "C. Thơ bốn chữ",
          "right": "3. Mỗi dòng thường bốn tiếng"
        },
        {
          "left": "D. Trạng ngữ mở rộng",
          "right": "4. Cụ thể hóa thông tin"
        }
      ],
      "dapAn": "A-1;B-2;C-3;D-4",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0055",
      "loai": "SORT",
      "cauHoi": "Sắp xếp bước viết đoạn văn cảm xúc về thơ.",
      "items": [
        "1. Xác định cảm xúc",
        "2. Chọn căn cứ từ bài thơ",
        "3. Phân tích và trình bày",
        "4. Chỉnh sửa"
      ],
      "dapAn": "1-2-3-4",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0056",
      "loai": "MCQ",
      "cauHoi": "Khi đọc hiểu, điều gì quan trọng nhất?",
      "A": "dựa vào văn bản",
      "B": "đoán đáp án",
      "C": "chỉ nhìn nhan đề",
      "D": "chỉ nhớ tác giả",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0057",
      "loai": "TRUEFALSE",
      "cauHoi": "Một nhận xét văn học cần có căn cứ từ văn bản.",
      "dapAn": "Đúng",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0058",
      "loai": "MULTI",
      "cauHoi": "Những yếu tố nào giúp câu trả lời đọc hiểu thuyết phục?",
      "A": "chi tiết văn bản",
      "B": "lí giải",
      "C": "dẫn chứng",
      "D": "ý kiến không căn cứ",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Vận dụng"
    },
    {
      "maCau": "VAN8-0059",
      "loai": "FILL",
      "cauHoi": "Khi tóm tắt, cần giữ các sự việc ________.",
      "dapAn": "chính",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0060",
      "loai": "MCQ",
      "cauHoi": "Khi đọc hiểu, điều gì quan trọng nhất?",
      "A": "dựa vào văn bản",
      "B": "đoán đáp án",
      "C": "chỉ nhìn nhan đề",
      "D": "chỉ nhớ tác giả",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0061",
      "loai": "TRUEFALSE",
      "cauHoi": "Một nhận xét văn học cần có căn cứ từ văn bản.",
      "dapAn": "Đúng",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0062",
      "loai": "MULTI",
      "cauHoi": "Những yếu tố nào giúp câu trả lời đọc hiểu thuyết phục?",
      "A": "chi tiết văn bản",
      "B": "lí giải",
      "C": "dẫn chứng",
      "D": "ý kiến không căn cứ",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Vận dụng"
    },
    {
      "maCau": "VAN8-0063",
      "loai": "FILL",
      "cauHoi": "Khi tóm tắt, cần giữ các sự việc ________.",
      "dapAn": "chính",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0064",
      "loai": "MCQ",
      "cauHoi": "Khi đọc hiểu, điều gì quan trọng nhất?",
      "A": "dựa vào văn bản",
      "B": "đoán đáp án",
      "C": "chỉ nhìn nhan đề",
      "D": "chỉ nhớ tác giả",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0065",
      "loai": "TRUEFALSE",
      "cauHoi": "Một nhận xét văn học cần có căn cứ từ văn bản.",
      "dapAn": "Đúng",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0066",
      "loai": "MULTI",
      "cauHoi": "Những yếu tố nào giúp câu trả lời đọc hiểu thuyết phục?",
      "A": "chi tiết văn bản",
      "B": "lí giải",
      "C": "dẫn chứng",
      "D": "ý kiến không căn cứ",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Vận dụng"
    },
    {
      "maCau": "VAN8-0067",
      "loai": "FILL",
      "cauHoi": "Khi tóm tắt, cần giữ các sự việc ________.",
      "dapAn": "chính",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0068",
      "loai": "MCQ",
      "cauHoi": "Khi đọc hiểu, điều gì quan trọng nhất?",
      "A": "dựa vào văn bản",
      "B": "đoán đáp án",
      "C": "chỉ nhìn nhan đề",
      "D": "chỉ nhớ tác giả",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0069",
      "loai": "TRUEFALSE",
      "cauHoi": "Một nhận xét văn học cần có căn cứ từ văn bản.",
      "dapAn": "Đúng",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0070",
      "loai": "MULTI",
      "cauHoi": "Những yếu tố nào giúp câu trả lời đọc hiểu thuyết phục?",
      "A": "chi tiết văn bản",
      "B": "lí giải",
      "C": "dẫn chứng",
      "D": "ý kiến không căn cứ",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Vận dụng"
    },
    {
      "maCau": "VAN8-0071",
      "loai": "MCQ",
      "cauHoi": "“Lá cờ thêu sáu chữ vàng” gắn với nhân vật nào?",
      "A": "Trần Quốc Toản",
      "B": "Nguyễn Trãi",
      "C": "Quang Trung",
      "D": "Lê Lợi",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 1: Câu chuyện của lịch sử",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0072",
      "loai": "MCQ",
      "cauHoi": "“Quang Trung đại phá quân Thanh” tái hiện chiến thắng của phong trào nào?",
      "A": "Tây Sơn",
      "B": "Lam Sơn",
      "C": "Cần Vương",
      "D": "Đông Du",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 1: Câu chuyện của lịch sử",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0073",
      "loai": "MCQ",
      "cauHoi": "Chủ đề của tác phẩm là gì?",
      "A": "vấn đề trung tâm hoặc thông điệp chính",
      "B": "tên nhân vật",
      "C": "số trang",
      "D": "năm in",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 1: Câu chuyện của lịch sử",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0074",
      "loai": "MCQ",
      "cauHoi": "Biệt ngữ xã hội là gì?",
      "A": "từ ngữ theo quy ước của một nhóm người, dùng trong phạm vi hẹp",
      "B": "từ cổ",
      "C": "mọi từ phổ thông",
      "D": "từ khoa học",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 1: Câu chuyện của lịch sử",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0075",
      "loai": "MCQ",
      "cauHoi": "“Ta đi tới” của Tố Hữu thể hiện cảm xúc nào?",
      "A": "niềm vui và tự hào về đất nước",
      "B": "nỗi sợ",
      "C": "sự hài hước",
      "D": "tình yêu đôi lứa",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 1: Câu chuyện của lịch sử",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0076",
      "loai": "MCQ",
      "cauHoi": "Viết bài văn kể lại chuyến tham quan di tích cần chú ý gì?",
      "A": "trình tự chuyến đi, chi tiết và cảm xúc",
      "B": "chỉ liệt kê",
      "C": "chỉ thời tiết",
      "D": "không cần cảm xúc",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 1: Câu chuyện của lịch sử",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0077",
      "loai": "TRUEFALSE",
      "cauHoi": "Truyện lịch sử có thể kết hợp sự kiện lịch sử với hư cấu nghệ thuật.",
      "dapAn": "Đúng",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 1",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0078",
      "loai": "MULTI",
      "cauHoi": "Khi đọc truyện lịch sử có thể chú ý gì?",
      "A": "bối cảnh",
      "B": "nhân vật",
      "C": "ngôn ngữ nhân vật",
      "D": "chỉ số liệu",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 1",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0079",
      "loai": "FILL",
      "cauHoi": "Từ ngữ dùng theo quy ước riêng của một nhóm người gọi là ________.",
      "dapAn": "biệt ngữ xã hội",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 1",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0080",
      "loai": "MATCH",
      "cauHoi": "Nối văn bản với đặc điểm.",
      "pairs": [
        {
          "left": "A. Lá cờ thêu sáu chữ vàng",
          "right": "1. Truyện lịch sử"
        },
        {
          "left": "B. Quang Trung đại phá quân Thanh",
          "right": "2. Tái hiện sự kiện lịch sử"
        },
        {
          "left": "C. Ta đi tới",
          "right": "3. Thơ trữ tình"
        }
      ],
      "dapAn": "A-1;B-2;C-3",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 1",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0081",
      "loai": "SORT",
      "cauHoi": "Sắp xếp các bước kể lại chuyến đi.",
      "items": [
        "1. Giới thiệu chuyến đi",
        "2. Kể theo trình tự",
        "3. Nêu ấn tượng/cảm xúc",
        "4. Chỉnh sửa"
      ],
      "dapAn": "1-2-3-4",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 1",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0082",
      "loai": "MCQ",
      "cauHoi": "“Thu điếu” thuộc thể thơ nào?",
      "A": "thất ngôn bát cú Đường luật",
      "B": "lục bát",
      "C": "năm chữ",
      "D": "song thất lục bát",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 2: Vẻ đẹp cổ điển",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0083",
      "loai": "MCQ",
      "cauHoi": "“Thiên Trường vãn vọng” là tác phẩm của ai?",
      "A": "Trần Nhân Tông",
      "B": "Nguyễn Du",
      "C": "Hồ Chí Minh",
      "D": "Tố Hữu",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 2: Vẻ đẹp cổ điển",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0084",
      "loai": "MCQ",
      "cauHoi": "Thơ Đường luật chú trọng những yếu tố nào?",
      "A": "niêm, luật, vần, đối, bố cục",
      "B": "chỉ số câu",
      "C": "chỉ nhịp",
      "D": "không cần vần",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 2: Vẻ đẹp cổ điển",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0085",
      "loai": "MCQ",
      "cauHoi": "“Ca Huế trên sông Hương” giúp khám phá điều gì?",
      "A": "vẻ đẹp văn hóa nghệ thuật của Huế",
      "B": "lịch sử quân sự",
      "C": "khoa học",
      "D": "thể thao",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 2: Vẻ đẹp cổ điển",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0086",
      "loai": "MCQ",
      "cauHoi": "Khi phân tích thơ thất ngôn bát cú cần chú ý gì?",
      "A": "bố cục, hình ảnh, ngôn ngữ và nghệ thuật thể thơ",
      "B": "chỉ tiểu sử",
      "C": "chỉ năm xuất bản",
      "D": "chỉ số trang",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 2: Vẻ đẹp cổ điển",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0087",
      "loai": "TRUEFALSE",
      "cauHoi": "Phân tích thơ Đường luật chỉ cần kể lại nội dung.",
      "dapAn": "Sai",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0088",
      "loai": "MULTI",
      "cauHoi": "Những yếu tố nào góp phần tạo vẻ đẹp cổ điển?",
      "A": "thi liệu",
      "B": "hình ảnh thiên nhiên",
      "C": "niêm luật",
      "D": "câu văn hành chính",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0089",
      "loai": "FILL",
      "cauHoi": "Bài thơ thất ngôn bát cú thường có ________ câu.",
      "dapAn": "tám",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 2",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN8-0090",
      "loai": "MATCH",
      "cauHoi": "Nối thể loại với đặc điểm.",
      "pairs": [
        {
          "left": "A. Thất ngôn bát cú",
          "right": "1. Tám câu, mỗi câu bảy tiếng"
        },
        {
          "left": "B. Tứ tuyệt",
          "right": "2. Bốn câu"
        },
        {
          "left": "C. Văn bản văn hóa",
          "right": "3. Cung cấp tri thức về nét văn hóa"
        }
      ],
      "dapAn": "A-1;B-2;C-3",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0091",
      "loai": "SORT",
      "cauHoi": "Sắp xếp các bước phân tích thơ.",
      "items": [
        "1. Giới thiệu tác giả/tác phẩm",
        "2. Xác định hình ảnh, mạch cảm xúc",
        "3. Phân tích nội dung và nghệ thuật",
        "4. Đánh giá"
      ],
      "dapAn": "1-2-3-4",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0092",
      "loai": "MCQ",
      "cauHoi": "Bằng chứng trong bài phân tích thơ nên là gì?",
      "A": "từ ngữ, hình ảnh, chi tiết tiêu biểu",
      "B": "chép toàn bài",
      "C": "tin đồn",
      "D": "nhận xét không căn cứ",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0093",
      "loai": "TRUEFALSE",
      "cauHoi": "Niêm, luật, vần, đối là những đặc điểm cần lưu ý khi đọc thơ Đường luật.",
      "dapAn": "Đúng",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0094",
      "loai": "MULTI",
      "cauHoi": "Khi cảm nhận một bài thơ có thể xem xét gì?",
      "A": "hình ảnh",
      "B": "từ ngữ",
      "C": "nhịp điệu, giọng điệu",
      "D": "màu giấy",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0095",
      "loai": "MCQ",
      "cauHoi": "Một nhận xét về tác phẩm văn học cần dựa vào đâu?",
      "A": "chi tiết và bằng chứng trong văn bản",
      "B": "đoán ý",
      "C": "chỉ nhan đề",
      "D": "chỉ tiểu sử",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 1-2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0096",
      "loai": "TRUEFALSE",
      "cauHoi": "Phân tích tác phẩm cần kết hợp nội dung với nghệ thuật.",
      "dapAn": "Đúng",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 1-2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0097",
      "loai": "MULTI",
      "cauHoi": "Một bài phân tích thơ nên có gì?",
      "A": "luận điểm",
      "B": "lí lẽ",
      "C": "bằng chứng",
      "D": "thông tin không liên quan",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 1-2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0098",
      "loai": "MCQ",
      "cauHoi": "Một nhận xét về tác phẩm văn học cần dựa vào đâu?",
      "A": "chi tiết và bằng chứng trong văn bản",
      "B": "đoán ý",
      "C": "chỉ nhan đề",
      "D": "chỉ tiểu sử",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 1-2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0099",
      "loai": "TRUEFALSE",
      "cauHoi": "Phân tích tác phẩm cần kết hợp nội dung với nghệ thuật.",
      "dapAn": "Đúng",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 1-2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN8-0100",
      "loai": "MULTI",
      "cauHoi": "Một bài phân tích thơ nên có gì?",
      "A": "luận điểm",
      "B": "lí lẽ",
      "C": "bằng chứng",
      "D": "thông tin không liên quan",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Lớp 8 – Bài 1-2",
      "doKho": "Thông hiểu"
    }
  ]
};

const cauHoi = nganHangDe.cauHoi;
