const nganHangDe = {
  "thongTin": {
    "mon": "Ngữ văn",
    "khoi": "7",
    "ten": "Ngân hàng câu hỏi Ngữ văn 7",
    "phienBan": "2.0",
    "phamVi": "Toàn bộ kiến thức lớp 6 + Bài 1, Bài 2 lớp 7"
  },
  "cauHoi": [
    {
      "maCau": "VAN7-0001",
      "loai": "MCQ",
      "cauHoi": "Nhân vật trong truyện thường được khắc họa qua những phương diện nào?",
      "A": "ngoại hình, hành động, lời nói, suy nghĩ",
      "B": "chỉ tên",
      "C": "chỉ tuổi",
      "D": "chỉ quê quán",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tôi và các bạn",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0002",
      "loai": "MCQ",
      "cauHoi": "Cốt truyện là gì?",
      "A": "chuỗi sự việc được tổ chức thành câu chuyện",
      "B": "danh sách nhân vật",
      "C": "tiểu sử tác giả",
      "D": "tên tác phẩm",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tôi và các bạn",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0003",
      "loai": "MCQ",
      "cauHoi": "Ngôi kể thứ nhất thường dùng đại từ nào?",
      "A": "tôi",
      "B": "hắn",
      "C": "nó",
      "D": "họ",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tôi và các bạn",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0004",
      "loai": "TRUEFALSE",
      "cauHoi": "Người kể chuyện luôn chính là tác giả ngoài đời.",
      "dapAn": "Sai",
      "diem": 1,
      "chuDe": "Tôi và các bạn",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0005",
      "loai": "MCQ",
      "cauHoi": "Văn bản về gia đình thường làm nổi bật giá trị nào?",
      "A": "tình yêu thương và gắn bó",
      "B": "cạnh tranh",
      "C": "vật chất",
      "D": "danh vọng",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Gõ cửa trái tim",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0006",
      "loai": "MULTI",
      "cauHoi": "Một bài nói về vấn đề gia đình nên có những gì?",
      "A": "quan điểm rõ",
      "B": "lí lẽ phù hợp",
      "C": "ví dụ cụ thể",
      "D": "nói thật nhanh",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Gõ cửa trái tim",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0007",
      "loai": "MCQ",
      "cauHoi": "Khi trình bày ý kiến, cần làm gì trước?",
      "A": "xác định rõ vấn đề",
      "B": "đọc thuộc mọi thứ",
      "C": "không cần chuẩn bị",
      "D": "chỉ chọn hình ảnh",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Gõ cửa trái tim",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0008",
      "loai": "MCQ",
      "cauHoi": "Khi phân tích nhân vật, bằng chứng nên lấy từ đâu?",
      "A": "chi tiết trong văn bản",
      "B": "tin đồn",
      "C": "quảng cáo",
      "D": "ý kiến không căn cứ",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Yêu thương và chia sẻ",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0009",
      "loai": "TRUEFALSE",
      "cauHoi": "Phân tích nhân vật chỉ cần kể lại cốt truyện.",
      "dapAn": "Sai",
      "diem": 1,
      "chuDe": "Yêu thương và chia sẻ",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0010",
      "loai": "MCQ",
      "cauHoi": "Thơ lục bát gồm cặp câu cơ bản như thế nào?",
      "A": "6 tiếng và 8 tiếng",
      "B": "4 tiếng và 5 tiếng",
      "C": "5 tiếng và 7 tiếng",
      "D": "7 tiếng và 7 tiếng",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Quê hương yêu dấu",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0011",
      "loai": "MCQ",
      "cauHoi": "Ca dao gắn với điều gì?",
      "A": "đời sống và tình cảm nhân dân",
      "B": "khoa học",
      "C": "luật pháp",
      "D": "tin tức",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Quê hương yêu dấu",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0012",
      "loai": "FILL",
      "cauHoi": "Thể thơ gồm câu sáu tiếng và câu tám tiếng gọi là ________.",
      "dapAn": "lục bát",
      "diem": 1,
      "chuDe": "Quê hương yêu dấu",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0013",
      "loai": "MCQ",
      "cauHoi": "Du kí thường ghi lại điều gì?",
      "A": "trải nghiệm, quan sát và cảm nhận",
      "B": "công thức",
      "C": "luật chơi",
      "D": "bảng số liệu",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Những nẻo đường xứ sở",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0014",
      "loai": "TRUEFALSE",
      "cauHoi": "Du kí có thể kết hợp kể, tả và biểu cảm.",
      "dapAn": "Đúng",
      "diem": 1,
      "chuDe": "Những nẻo đường xứ sở",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0015",
      "loai": "MCQ",
      "cauHoi": "Khi kể về chuyến đi, nên kết hợp sự việc với gì?",
      "A": "quan sát và cảm xúc",
      "B": "chỉ số liệu",
      "C": "chỉ lời thoại",
      "D": "chỉ nhận xét",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Những nẻo đường xứ sở",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0016",
      "loai": "MCQ",
      "cauHoi": "“Thánh Gióng” thuộc thể loại nào?",
      "A": "truyền thuyết",
      "B": "truyện cười",
      "C": "tản văn",
      "D": "kí",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Chuyện kể về những người anh hùng",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0017",
      "loai": "MCQ",
      "cauHoi": "“Sơn Tinh, Thủy Tinh” gắn với hiện tượng nào?",
      "A": "lũ lụt",
      "B": "động đất",
      "C": "sương mù",
      "D": "hạn hán",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Chuyện kể về những người anh hùng",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0018",
      "loai": "MULTI",
      "cauHoi": "Truyền thuyết thường có những yếu tố nào?",
      "A": "nhân vật/sự kiện gắn lịch sử",
      "B": "yếu tố kì ảo",
      "C": "cách đánh giá của nhân dân",
      "D": "số liệu khoa học bắt buộc",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Chuyện kể về những người anh hùng",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0019",
      "loai": "MCQ",
      "cauHoi": "Đặc điểm thường gặp của truyện cổ tích là gì?",
      "A": "yếu tố kì ảo và ước mơ công bằng",
      "B": "ghi chép lịch sử",
      "C": "số liệu khoa học",
      "D": "không có nhân vật",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Thế giới cổ tích",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0020",
      "loai": "TRUEFALSE",
      "cauHoi": "Cổ tích hoàn toàn không có yếu tố tưởng tượng.",
      "dapAn": "Sai",
      "diem": 1,
      "chuDe": "Thế giới cổ tích",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0021",
      "loai": "MCQ",
      "cauHoi": "Tôn trọng sự khác biệt giúp con người như thế nào?",
      "A": "hiểu và ứng xử văn minh hơn",
      "B": "xa cách hơn",
      "C": "không đối thoại",
      "D": "đánh giá vội vàng",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Khác biệt và gần gũi",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0022",
      "loai": "MCQ",
      "cauHoi": "Khi kể lại một sự việc, yếu tố nào giúp bài viết rõ ràng?",
      "A": "trình tự hợp lí",
      "B": "chỉ tính từ",
      "C": "chỉ đối thoại",
      "D": "không có thời gian",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Khác biệt và gần gũi",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0023",
      "loai": "MCQ",
      "cauHoi": "Mục đích chính của văn bản thông tin là gì?",
      "A": "cung cấp và tổ chức thông tin",
      "B": "chỉ kể chuyện",
      "C": "chỉ biểu cảm",
      "D": "chỉ gây cười",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Trái Đất – ngôi nhà chung",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0024",
      "loai": "MULTI",
      "cauHoi": "Văn bản thông tin có thể sử dụng những yếu tố nào?",
      "A": "tiêu đề",
      "B": "đề mục",
      "C": "số liệu/hình ảnh",
      "D": "nhân vật hư cấu bắt buộc",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Trái Đất – ngôi nhà chung",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0025",
      "loai": "MCQ",
      "cauHoi": "Khi giới thiệu sách nên nêu gì?",
      "A": "tên, tác giả, nội dung và giá trị",
      "B": "chỉ giá tiền",
      "C": "chỉ màu bìa",
      "D": "chỉ số trang",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Cuốn sách tôi yêu",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0026",
      "loai": "TRUEFALSE",
      "cauHoi": "Giới thiệu sách nên nêu lí do vì sao cuốn sách đáng đọc.",
      "dapAn": "Đúng",
      "diem": 1,
      "chuDe": "Cuốn sách tôi yêu",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0027",
      "loai": "MCQ",
      "cauHoi": "Trạng ngữ thường bổ sung thông tin về gì?",
      "A": "thời gian, nơi chốn, nguyên nhân, mục đích...",
      "B": "chỉ chủ ngữ",
      "C": "chỉ số lượng",
      "D": "chỉ tên người",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tiếng Việt 6",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0028",
      "loai": "MCQ",
      "cauHoi": "Thành phần trung tâm của cụm danh từ là gì?",
      "A": "danh từ",
      "B": "động từ",
      "C": "tính từ",
      "D": "phó từ",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tiếng Việt 6",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0029",
      "loai": "MCQ",
      "cauHoi": "Thành phần trung tâm của cụm động từ là gì?",
      "A": "động từ",
      "B": "danh từ",
      "C": "tính từ",
      "D": "quan hệ từ",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tiếng Việt 6",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0030",
      "loai": "MCQ",
      "cauHoi": "Nhân hóa là gì?",
      "A": "gán đặc điểm của con người cho sự vật",
      "B": "đối chiếu",
      "C": "lặp từ",
      "D": "nói giảm",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tiếng Việt 6",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0031",
      "loai": "MCQ",
      "cauHoi": "So sánh giúp cách diễn đạt như thế nào?",
      "A": "cụ thể, sinh động",
      "B": "khó hiểu hơn",
      "C": "không có hình ảnh",
      "D": "chỉ có số liệu",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tiếng Việt 6",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0032",
      "loai": "MCQ",
      "cauHoi": "Điệp ngữ là gì?",
      "A": "lặp lại từ ngữ có chủ ý",
      "B": "dùng từ địa phương",
      "C": "đảo câu",
      "D": "dùng số liệu",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tiếng Việt 6",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0033",
      "loai": "FILL",
      "cauHoi": "Lặp lại từ ngữ có chủ ý để nhấn mạnh gọi là ________.",
      "dapAn": "điệp ngữ",
      "diem": 1,
      "chuDe": "Tiếng Việt 6",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0034",
      "loai": "MCQ",
      "cauHoi": "Dấu ngoặc kép có thể dùng để đánh dấu gì?",
      "A": "lời dẫn trực tiếp hoặc từ ngữ đặc biệt",
      "B": "câu hỏi",
      "C": "chủ ngữ",
      "D": "dấu chấm",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tiếng Việt 6",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0035",
      "loai": "MCQ",
      "cauHoi": "Ẩn dụ là biện pháp gọi tên sự vật dựa trên quan hệ nào?",
      "A": "tương đồng",
      "B": "thời gian",
      "C": "địa điểm",
      "D": "số lượng",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tiếng Việt 6",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0036",
      "loai": "MCQ",
      "cauHoi": "Hoán dụ thường dựa trên quan hệ nào?",
      "A": "gần gũi",
      "B": "tương phản tuyệt đối",
      "C": "ngẫu nhiên",
      "D": "không liên quan",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tiếng Việt 6",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0037",
      "loai": "MATCH",
      "cauHoi": "Nối khái niệm với đặc điểm.",
      "pairs": [
        {
          "left": "A. Nhân hóa",
          "right": "1. Gán đặc điểm người cho vật"
        },
        {
          "left": "B. So sánh",
          "right": "2. Đối chiếu sự vật"
        },
        {
          "left": "C. Điệp ngữ",
          "right": "3. Lặp từ ngữ có chủ ý"
        },
        {
          "left": "D. Lục bát",
          "right": "4. Thể thơ 6–8"
        }
      ],
      "dapAn": "A-1;B-2;C-3;D-4",
      "diem": 1,
      "chuDe": "Tổng hợp lớp 6",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0038",
      "loai": "SORT",
      "cauHoi": "Sắp xếp các bước viết bài kể trải nghiệm.",
      "items": [
        "1. Xác định trải nghiệm",
        "2. Sắp xếp sự việc",
        "3. Kể kết hợp cảm xúc",
        "4. Chỉnh sửa"
      ],
      "dapAn": "1-2-3-4",
      "diem": 1,
      "chuDe": "Tổng hợp lớp 6",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0039",
      "loai": "MCQ",
      "cauHoi": "Chi tiết hành động của nhân vật có thể giúp người đọc nhận ra điều gì?",
      "A": "tính cách",
      "B": "giá sách",
      "C": "số chương",
      "D": "nhà xuất bản",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tôi và các bạn",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0040",
      "loai": "MCQ",
      "cauHoi": "Một ý kiến tốt cần được hỗ trợ bằng gì?",
      "A": "lí lẽ và dẫn chứng",
      "B": "chỉ cảm xúc",
      "C": "chỉ khẩu hiệu",
      "D": "chỉ hình ảnh",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Gõ cửa trái tim",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0041",
      "loai": "TRUEFALSE",
      "cauHoi": "Ca dao có thể thể hiện tình yêu quê hương.",
      "dapAn": "Đúng",
      "diem": 1,
      "chuDe": "Quê hương yêu dấu",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0042",
      "loai": "MCQ",
      "cauHoi": "Người viết du kí thường chú ý đến yếu tố nào?",
      "A": "cảnh vật và trải nghiệm cá nhân",
      "B": "chỉ số liệu",
      "C": "chỉ lời thoại",
      "D": "chỉ nhân vật hư cấu",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Những nẻo đường xứ sở",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0043",
      "loai": "MCQ",
      "cauHoi": "Yếu tố kì ảo trong truyền thuyết thường góp phần thể hiện điều gì?",
      "A": "ước mơ và cách nhìn của nhân dân",
      "B": "kĩ thuật khoa học",
      "C": "giá thành sách",
      "D": "thời tiết thực tế",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Chuyện kể về những người anh hùng",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0044",
      "loai": "TRUEFALSE",
      "cauHoi": "Kết thúc có hậu thường thể hiện niềm tin vào điều tốt đẹp.",
      "dapAn": "Đúng",
      "diem": 1,
      "chuDe": "Thế giới cổ tích",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0045",
      "loai": "MCQ",
      "cauHoi": "Khi viết về một trải nghiệm, ngôi kể thứ nhất thường tạo hiệu quả gì?",
      "A": "gần gũi và trực tiếp",
      "B": "khách quan tuyệt đối",
      "C": "không có cảm xúc",
      "D": "không có người kể",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Khác biệt và gần gũi",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0046",
      "loai": "MCQ",
      "cauHoi": "Số liệu trong văn bản thông tin có tác dụng gì?",
      "A": "làm thông tin cụ thể, đáng tin cậy hơn",
      "B": "làm mất thông tin",
      "C": "chỉ để trang trí",
      "D": "thay thế tiêu đề",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Trái Đất – ngôi nhà chung",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0047",
      "loai": "MCQ",
      "cauHoi": "Một lời giới thiệu sách tốt nên hướng đến điều gì?",
      "A": "giúp người nghe hiểu và hứng thú với sách",
      "B": "khiến người nghe mua ngay",
      "C": "chỉ nêu giá",
      "D": "chỉ đọc mục lục",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Cuốn sách tôi yêu",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0048",
      "loai": "FILL",
      "cauHoi": "Ý nghĩa của từ ngữ trong câu còn có thể được hiểu nhờ ________.",
      "dapAn": "ngữ cảnh",
      "diem": 1,
      "chuDe": "Tiếng Việt 6",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0049",
      "loai": "MCQ",
      "cauHoi": "Cụm tính từ có thành phần trung tâm là gì?",
      "A": "tính từ",
      "B": "danh từ",
      "C": "động từ",
      "D": "quan hệ từ",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tiếng Việt 6",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0050",
      "loai": "TRUEFALSE",
      "cauHoi": "Một đoạn văn cần có sự liên kết về nội dung.",
      "dapAn": "Đúng",
      "diem": 1,
      "chuDe": "Tiếng Việt 6",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0051",
      "loai": "MCQ",
      "cauHoi": "Khi đọc hiểu, bằng chứng quan trọng nhất là gì?",
      "A": "chi tiết được thể hiện trong văn bản",
      "B": "tin đồn",
      "C": "đoán ý",
      "D": "ý kiến người khác",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tiếng Việt 6",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0052",
      "loai": "MULTI",
      "cauHoi": "Những cách nào giúp bài viết mạch lạc?",
      "A": "sắp xếp ý hợp lí",
      "B": "dùng từ nối phù hợp",
      "C": "giữ chủ đề thống nhất",
      "D": "thêm thật nhiều ý ngoài đề",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Tiếng Việt 6",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0053",
      "loai": "MCQ",
      "cauHoi": "Mục đích của việc lập dàn ý là gì?",
      "A": "sắp xếp nội dung trước khi viết",
      "B": "làm bài dài hơn",
      "C": "thay thế bài viết",
      "D": "chỉ để trang trí",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tiếng Việt 6",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0054",
      "loai": "MCQ",
      "cauHoi": "“Bầy chim chìa vôi” tập trung thể hiện thế giới nào?",
      "A": "tuổi thơ và tình cảm trong trẻo",
      "B": "đời sống cung đình",
      "C": "chiến tranh hiện đại",
      "D": "thương mại",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1: Bầu trời tuổi thơ",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0055",
      "loai": "MCQ",
      "cauHoi": "Tóm tắt văn bản cần ưu tiên điều gì?",
      "A": "sự việc chính và trình tự hợp lí",
      "B": "mọi chi tiết",
      "C": "mọi lời thoại",
      "D": "mọi câu văn",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1: Bầu trời tuổi thơ",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0056",
      "loai": "MCQ",
      "cauHoi": "Mở rộng trạng ngữ bằng cụm từ có tác dụng gì?",
      "A": "cung cấp thông tin cụ thể hơn",
      "B": "làm câu sai",
      "C": "xóa trạng ngữ",
      "D": "chỉ đổi dấu câu",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1: Bầu trời tuổi thơ",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0057",
      "loai": "FILL",
      "cauHoi": "Trạng ngữ có thể được mở rộng bằng một ________ để thông tin cụ thể hơn.",
      "dapAn": "cụm từ",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1: Bầu trời tuổi thơ",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0058",
      "loai": "TRUEFALSE",
      "cauHoi": "Tóm tắt là chép lại nguyên văn toàn bộ văn bản.",
      "dapAn": "Sai",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1: Bầu trời tuổi thơ",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0059",
      "loai": "MULTI",
      "cauHoi": "Khi tóm tắt truyện nên giữ gì?",
      "A": "nhân vật chính",
      "B": "sự việc chính",
      "C": "trình tự quan trọng",
      "D": "mọi chi tiết phụ",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1: Bầu trời tuổi thơ",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0060",
      "loai": "MCQ",
      "cauHoi": "Một bản tóm tắt tốt cần như thế nào?",
      "A": "ngắn gọn nhưng đúng nội dung",
      "B": "dài hơn bản gốc",
      "C": "thêm tình tiết",
      "D": "đổi kết thúc",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1: Bầu trời tuổi thơ",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0061",
      "loai": "MCQ",
      "cauHoi": "Khi kể lại một trải nghiệm, chi tiết tiêu biểu giúp gì?",
      "A": "làm câu chuyện tập trung",
      "B": "làm mất mạch",
      "C": "kéo dài vô ích",
      "D": "xóa cảm xúc",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1: Bầu trời tuổi thơ",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0062",
      "loai": "MCQ",
      "cauHoi": "Bài nói về trải nghiệm cần chú ý gì?",
      "A": "trình tự, nội dung và cảm xúc",
      "B": "chỉ tốc độ",
      "C": "chỉ hình ảnh",
      "D": "chỉ số slide",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1: Bầu trời tuổi thơ",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0063",
      "loai": "MCQ",
      "cauHoi": "“Đồng dao mùa xuân” thuộc thể loại nào?",
      "A": "thơ",
      "B": "truyện",
      "C": "kịch",
      "D": "nghị luận",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 2: Khúc nhạc tâm hồn",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0064",
      "loai": "MCQ",
      "cauHoi": "“Gặp lá cơm nếp” gợi nổi bật tình cảm nào?",
      "A": "tình yêu mẹ và quê hương",
      "B": "sự ganh đua",
      "C": "tình yêu vật chất",
      "D": "nỗi sợ",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 2: Khúc nhạc tâm hồn",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0065",
      "loai": "MCQ",
      "cauHoi": "Thơ bốn chữ được nhận biết chủ yếu dựa vào đâu?",
      "A": "số tiếng trong mỗi dòng",
      "B": "số khổ",
      "C": "tên tác giả",
      "D": "số nhân vật",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 2: Khúc nhạc tâm hồn",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0066",
      "loai": "MCQ",
      "cauHoi": "Đoạn văn ghi lại cảm xúc về thơ cần dựa vào gì?",
      "A": "hình ảnh, từ ngữ, nhịp điệu và nội dung",
      "B": "chỉ tiểu sử",
      "C": "chỉ nhan đề",
      "D": "chỉ năm sáng tác",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 2: Khúc nhạc tâm hồn",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0067",
      "loai": "FILL",
      "cauHoi": "Thơ bốn chữ là thể thơ mỗi dòng thường có ________ tiếng.",
      "dapAn": "bốn",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 2: Khúc nhạc tâm hồn",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0068",
      "loai": "TRUEFALSE",
      "cauHoi": "Cảm xúc về bài thơ cần có căn cứ từ văn bản.",
      "dapAn": "Đúng",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 2: Khúc nhạc tâm hồn",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0069",
      "loai": "MULTI",
      "cauHoi": "Khi phân tích thơ có thể chú ý những gì?",
      "A": "hình ảnh",
      "B": "từ ngữ",
      "C": "nhịp điệu",
      "D": "màu giấy",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 2: Khúc nhạc tâm hồn",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0070",
      "loai": "MCQ",
      "cauHoi": "Một đoạn văn cảm xúc tốt cần tránh điều gì?",
      "A": "nhận xét chung chung không có căn cứ",
      "B": "nêu cảm xúc",
      "C": "dẫn hình ảnh",
      "D": "liên hệ",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 2: Khúc nhạc tâm hồn",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0071",
      "loai": "MCQ",
      "cauHoi": "Mạch cảm xúc giúp người đọc hiểu điều gì?",
      "A": "sự vận động của tình cảm và suy nghĩ",
      "B": "số trang",
      "C": "giá sách",
      "D": "nhà in",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 2: Khúc nhạc tâm hồn",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0072",
      "loai": "MATCH",
      "cauHoi": "Nối nội dung với kĩ năng.",
      "pairs": [
        {
          "left": "A. Tóm tắt",
          "right": "1. Giữ sự việc chính"
        },
        {
          "left": "B. Cảm nhận thơ",
          "right": "2. Dựa vào hình ảnh, từ ngữ"
        },
        {
          "left": "C. Thơ bốn chữ",
          "right": "3. Mỗi dòng thường bốn tiếng"
        },
        {
          "left": "D. Trạng ngữ mở rộng",
          "right": "4. Cụ thể hóa thông tin"
        }
      ],
      "dapAn": "A-1;B-2;C-3;D-4",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0073",
      "loai": "SORT",
      "cauHoi": "Sắp xếp bước viết đoạn văn cảm xúc về thơ.",
      "items": [
        "1. Xác định cảm xúc",
        "2. Chọn căn cứ từ bài thơ",
        "3. Phân tích và trình bày",
        "4. Chỉnh sửa"
      ],
      "dapAn": "1-2-3-4",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0074",
      "loai": "MCQ",
      "cauHoi": "Khi đọc hiểu, điều gì quan trọng nhất?",
      "A": "dựa vào văn bản",
      "B": "đoán đáp án",
      "C": "chỉ nhìn nhan đề",
      "D": "chỉ nhớ tác giả",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0075",
      "loai": "TRUEFALSE",
      "cauHoi": "Một nhận xét văn học cần có căn cứ từ văn bản.",
      "dapAn": "Đúng",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0076",
      "loai": "MULTI",
      "cauHoi": "Những yếu tố nào giúp câu trả lời đọc hiểu thuyết phục?",
      "A": "chi tiết văn bản",
      "B": "lí giải",
      "C": "dẫn chứng",
      "D": "ý kiến không căn cứ",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Vận dụng"
    },
    {
      "maCau": "VAN7-0077",
      "loai": "FILL",
      "cauHoi": "Khi tóm tắt, cần giữ các sự việc ________.",
      "dapAn": "chính",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0078",
      "loai": "MCQ",
      "cauHoi": "Khi đọc hiểu, điều gì quan trọng nhất?",
      "A": "dựa vào văn bản",
      "B": "đoán đáp án",
      "C": "chỉ nhìn nhan đề",
      "D": "chỉ nhớ tác giả",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0079",
      "loai": "TRUEFALSE",
      "cauHoi": "Một nhận xét văn học cần có căn cứ từ văn bản.",
      "dapAn": "Đúng",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0080",
      "loai": "MULTI",
      "cauHoi": "Những yếu tố nào giúp câu trả lời đọc hiểu thuyết phục?",
      "A": "chi tiết văn bản",
      "B": "lí giải",
      "C": "dẫn chứng",
      "D": "ý kiến không căn cứ",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Vận dụng"
    },
    {
      "maCau": "VAN7-0081",
      "loai": "FILL",
      "cauHoi": "Khi tóm tắt, cần giữ các sự việc ________.",
      "dapAn": "chính",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0082",
      "loai": "MCQ",
      "cauHoi": "Khi đọc hiểu, điều gì quan trọng nhất?",
      "A": "dựa vào văn bản",
      "B": "đoán đáp án",
      "C": "chỉ nhìn nhan đề",
      "D": "chỉ nhớ tác giả",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0083",
      "loai": "TRUEFALSE",
      "cauHoi": "Một nhận xét văn học cần có căn cứ từ văn bản.",
      "dapAn": "Đúng",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0084",
      "loai": "MULTI",
      "cauHoi": "Những yếu tố nào giúp câu trả lời đọc hiểu thuyết phục?",
      "A": "chi tiết văn bản",
      "B": "lí giải",
      "C": "dẫn chứng",
      "D": "ý kiến không căn cứ",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Vận dụng"
    },
    {
      "maCau": "VAN7-0085",
      "loai": "FILL",
      "cauHoi": "Khi tóm tắt, cần giữ các sự việc ________.",
      "dapAn": "chính",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0086",
      "loai": "MCQ",
      "cauHoi": "Khi đọc hiểu, điều gì quan trọng nhất?",
      "A": "dựa vào văn bản",
      "B": "đoán đáp án",
      "C": "chỉ nhìn nhan đề",
      "D": "chỉ nhớ tác giả",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0087",
      "loai": "TRUEFALSE",
      "cauHoi": "Một nhận xét văn học cần có căn cứ từ văn bản.",
      "dapAn": "Đúng",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0088",
      "loai": "MULTI",
      "cauHoi": "Những yếu tố nào giúp câu trả lời đọc hiểu thuyết phục?",
      "A": "chi tiết văn bản",
      "B": "lí giải",
      "C": "dẫn chứng",
      "D": "ý kiến không căn cứ",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Vận dụng"
    },
    {
      "maCau": "VAN7-0089",
      "loai": "FILL",
      "cauHoi": "Khi tóm tắt, cần giữ các sự việc ________.",
      "dapAn": "chính",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0090",
      "loai": "MCQ",
      "cauHoi": "Khi đọc hiểu, điều gì quan trọng nhất?",
      "A": "dựa vào văn bản",
      "B": "đoán đáp án",
      "C": "chỉ nhìn nhan đề",
      "D": "chỉ nhớ tác giả",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0091",
      "loai": "TRUEFALSE",
      "cauHoi": "Một nhận xét văn học cần có căn cứ từ văn bản.",
      "dapAn": "Đúng",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0092",
      "loai": "MULTI",
      "cauHoi": "Những yếu tố nào giúp câu trả lời đọc hiểu thuyết phục?",
      "A": "chi tiết văn bản",
      "B": "lí giải",
      "C": "dẫn chứng",
      "D": "ý kiến không căn cứ",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Vận dụng"
    },
    {
      "maCau": "VAN7-0093",
      "loai": "FILL",
      "cauHoi": "Khi tóm tắt, cần giữ các sự việc ________.",
      "dapAn": "chính",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1-2",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0094",
      "loai": "MCQ",
      "cauHoi": "Khi trả lời câu hỏi đọc hiểu, nguyên tắc quan trọng nhất là gì?",
      "A": "dựa vào văn bản và yêu cầu câu hỏi",
      "B": "đoán theo cảm tính",
      "C": "chỉ nhìn nhan đề",
      "D": "chỉ nhớ tên tác giả",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Tổng hợp lớp 6–7",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0095",
      "loai": "TRUEFALSE",
      "cauHoi": "Một câu trả lời đọc hiểu tốt cần có căn cứ phù hợp từ văn bản.",
      "dapAn": "Đúng",
      "diem": 1,
      "chuDe": "Tổng hợp lớp 6–7",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0096",
      "loai": "MULTI",
      "cauHoi": "Những yếu tố nào giúp bài viết có sức thuyết phục?",
      "A": "luận điểm rõ",
      "B": "lí lẽ hợp lí",
      "C": "bằng chứng phù hợp",
      "D": "thêm nhiều ý ngoài đề",
      "dapAn": "A,B,C",
      "diem": 1,
      "chuDe": "Tổng hợp lớp 6–7",
      "doKho": "Vận dụng"
    },
    {
      "maCau": "VAN7-0097",
      "loai": "FILL",
      "cauHoi": "Trong bài nghị luận, ________ dùng để làm sáng tỏ luận điểm.",
      "dapAn": "bằng chứng",
      "diem": 1,
      "chuDe": "Tổng hợp lớp 6–7",
      "doKho": "Nhận biết"
    },
    {
      "maCau": "VAN7-0098",
      "loai": "MCQ",
      "cauHoi": "Khi tóm tắt, những chi tiết phụ thường được xử lí như thế nào?",
      "A": "lược bỏ hoặc khái quát",
      "B": "chép nguyên văn",
      "C": "phóng đại",
      "D": "đổi thành sự việc mới",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 1: Bầu trời tuổi thơ",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0099",
      "loai": "MCQ",
      "cauHoi": "Khi cảm nhận một bài thơ, nhận xét cần dựa vào yếu tố nào?",
      "A": "từ ngữ, hình ảnh và nhịp điệu",
      "B": "chỉ tên tác giả",
      "C": "chỉ số trang",
      "D": "chỉ năm xuất bản",
      "dapAn": "A",
      "diem": 1,
      "chuDe": "Lớp 7 – Bài 2: Khúc nhạc tâm hồn",
      "doKho": "Thông hiểu"
    },
    {
      "maCau": "VAN7-0100",
      "loai": "MATCH",
      "cauHoi": "Nối kĩ năng với yêu cầu.",
      "pairs": [
        {
          "left": "A. Tóm tắt",
          "right": "1. Giữ sự việc chính"
        },
        {
          "left": "B. Phân tích nhân vật",
          "right": "2. Dựa vào hành động, lời nói, suy nghĩ"
        },
        {
          "left": "C. Cảm nhận thơ",
          "right": "3. Dựa vào hình ảnh, từ ngữ"
        },
        {
          "left": "D. Nghị luận",
          "right": "4. Có luận điểm, lí lẽ, bằng chứng"
        }
      ],
      "dapAn": "A-1;B-2;C-3;D-4",
      "diem": 1,
      "chuDe": "Lớp 6–7",
      "doKho": "Thông hiểu"
    }
  ]
};

const cauHoi = nganHangDe.cauHoi;
